#!/bin/sh
# without '-e', because some WEB codes are buggy

SHRTOPTS=cnpt:
LONGOPTS=changes,new,pdftocfront,tex:

CHANGES=false
PDFTOCFRONT=false
TEX=tex

getopt -T >/dev/null

if [ $? -eq 4 ] # Check for Linux-getopt with extensions
then OPTS=$(getopt -n downloadable-programs -o $SHRTOPTS -l $LONGOPTS -- "$@")
else OPTS=$(getopt $SHRTOPTS $*)
fi

if [ $? -eq 0 ] # Check return code from getopt
then eval set -- "$OPTS"
else echo "Failed to parse options." >&2; exit 1; fi

while true
do
	case "$1" in
		-c | --changes ) CHANGES=true; shift ;;
		-n | --new ) export TEXINPUTS="/opt/github/web//:"; shift ;;
		-p | --pdftocfront ) PDFTOCFRONT=true; shift ;;
		-t | --tex ) TEX="$2"; shift 2 ;;
		-- ) shift; break ;;
		* ) break ;;
	esac
done

KNUTHWHERE=$(locate /bibtex.web)
KNUTHWARE=$(dirname $KNUTHWHERE)

for f in $KNUTHWARE/*.web
do
	echo $f
	if $CHANGES
	then weave $f $KNUTHWARE/$(basename $f .web).ch
	else weave $f
	fi
	f=$(basename $f .web)
	case $f in
		# purge conflict between bibtex.web and webmac.tex
		# 'E' no longer free to be active character
		"bibtex") sed -i -e "70,77d" $f.tex ;;
	esac
	if $PDFTOCFRONT
	then
		TEXINPUTS="/opt/github/cwebbin//:$TEXINPUTS"
		sed -i -e "1 s/\(webmac\)/\1 \\\\input pdfwebtocfront/" $f.tex
	fi
	echo $TEXINPUTS
	$TEX $f
	#exit
done
